"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-05-20 18:50:15.715309

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events_archive',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.String(length=40), nullable=True),
    sa.Column('actor_email_snapshot', sa.String(length=254), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_archive_archived_at', 'audit_events_archive', ['archived_at'], unique=False)
    op.create_index('ix_audit_archive_at_desc', 'audit_events_archive', [sa.literal_column('at DESC')], unique=False)
    op.create_table('external_epg_cache',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('channel_id', sa.String(length=80), nullable=False),
    sa.Column('airing_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('airing_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('show_title', sa.String(length=300), nullable=False),
    sa.Column('episode_title', sa.String(length=300), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'channel_id', 'airing_start', 'show_title', name='uq_epg_cache_provider_channel_start_show')
    )
    op.create_index('ix_epg_cache_airing_end', 'external_epg_cache', ['airing_end'], unique=False)
    op.create_index('ix_epg_cache_lookup', 'external_epg_cache', ['provider', 'channel_id', sa.literal_column('airing_start DESC')], unique=False)
    op.create_table('external_sensor_sources',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('scope_claims', sa.JSON(), nullable=True),
    sa.Column('tombstone_for', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index('ix_outbox_at', 'outbox_events', [sa.literal_column('at DESC')], unique=False)
    op.create_index('ix_outbox_entity', 'outbox_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_outbox_seq', 'outbox_events', ['seq'], unique=False)
    op.create_index('ix_outbox_tombstone', 'outbox_events', ['tombstone_for'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signup_requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invitation_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signup_requests_created_at', 'signup_requests', ['created_at'], unique=False)
    op.create_index('ix_signup_requests_email', 'signup_requests', ['email'], unique=False)
    op.create_index('ix_signup_requests_status', 'signup_requests', ['status'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_cursors',
    sa.Column('peer_hub_id', sa.String(length=40), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('peer_hub_id')
    )
    op.create_index('ix_sync_cursor_updated', 'sync_cursors', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tombstones',
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_outbox_seq', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_tombstone_created', 'tombstones', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_tombstone_entity_type', 'tombstones', ['entity_type'], unique=False)
    op.create_table('unregistered_auth_attempts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('claimed_device_id', sa.String(length=80), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('auth_present', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claimed_device_id', 'source_ip', 'endpoint', name='uq_unregistered_attempts_claim_ip_endpoint')
    )
    op.create_index('ix_unregistered_attempts_claim', 'unregistered_auth_attempts', ['claimed_device_id'], unique=False)
    op.create_index('ix_unregistered_attempts_last_seen', 'unregistered_auth_attempts', [sa.literal_column('last_seen_at DESC')], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tokens_valid_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attention_acks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('attention_id', sa.String(length=120), nullable=False),
    sa.Column('acked_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attention_id')
    )
    op.create_index('ix_attention_acks_attention_id', 'attention_acks', ['attention_id'], unique=False)
    op.create_index('ix_attention_acks_snooze_until', 'attention_acks', ['snooze_until'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.String(length=40), nullable=True),
    sa.Column('actor_email_snapshot', sa.String(length=254), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_actor', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_at_desc', 'audit_events', [sa.literal_column('at DESC')], unique=False)
    op.create_index('ix_audit_target', 'audit_events', ['target_type', 'target_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('hardware_model', sa.String(length=80), nullable=True),
    sa.Column('hardware_revision', sa.String(length=40), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('mac_address', sa.String(length=40), nullable=True),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('local_ip', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('site_id', sa.String(length=40), nullable=True),
    sa.Column('central_management_enabled', sa.Boolean(), nullable=False),
    sa.Column('registration_state', sa.String(length=20), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_qa_fixture', sa.Boolean(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('is_held_off', sa.Boolean(), nullable=False),
    sa.Column('desired_config', sa.JSON(), nullable=True),
    sa.Column('desired_mode', sa.String(length=40), nullable=True),
    sa.Column('last_reported_config', sa.JSON(), nullable=True),
    sa.Column('desired_config_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_config_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_recovery_mode', sa.Boolean(), nullable=True),
    sa.Column('reported_auto_recovery_triggered', sa.Boolean(), nullable=True),
    sa.Column('reported_last_known_good_restored', sa.Boolean(), nullable=True),
    sa.Column('reported_consecutive_unhealthy_boots', sa.Integer(), nullable=True),
    sa.Column('reported_in_captive_portal', sa.Boolean(), nullable=True),
    sa.Column('reported_central_enabled', sa.Boolean(), nullable=True),
    sa.Column('reported_central_registered', sa.Boolean(), nullable=True),
    sa.Column('reported_central_state', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_last_heartbeat_at', 'devices', ['last_heartbeat_at'], unique=False)
    op.create_index('ix_devices_mac_address', 'devices', ['mac_address'], unique=False)
    op.create_index('ix_devices_site_id', 'devices', ['site_id'], unique=False)
    op.create_table('external_sensor_samples',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['external_sensor_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_external_sensor_samples_source_sampled', 'external_sensor_samples', ['source_id', sa.literal_column('sampled_at DESC')], unique=False)
    op.create_table('firmware_releases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('download_url', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', 'channel', name='uq_firmware_version_channel')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invitations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('scope_payload', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_invitations_email', 'invitations', ['email'], unique=False)
    op.create_index('ix_invitations_expires_at', 'invitations', ['expires_at'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('email_snapshot', sa.String(length=254), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('consumed_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_resets_expires_at', 'password_resets', ['expires_at'], unique=False)
    op.create_index('ix_password_resets_user_id', 'password_resets', ['user_id'], unique=False)
    op.create_table('role_bindings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope_type', 'scope_id', name='uq_role_binding_scope')
    )
    op.create_index('ix_role_bindings_scope', 'role_bindings', ['scope_type', 'scope_id'], unique=False)
    op.create_index('ix_role_bindings_user', 'role_bindings', ['user_id'], unique=False)
    op.create_table('runtime_flags',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('runtime_settings',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('at_time_utc', sa.String(length=5), nullable=True),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('power_off_seconds', sa.Integer(), nullable=False),
    sa.Column('post_reboot_holdoff_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outcome', sa.String(length=40), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_enabled_next_run', 'schedules', ['enabled', 'next_run_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('ix_user_sessions_jti', 'user_sessions', ['jti'], unique=False)
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('watchdog_rules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('site_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('probe', sa.JSON(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('recovery_threshold', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('escalation', sa.JSON(), nullable=False),
    sa.Column('maintenance_windows', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_streak', sa.Integer(), nullable=False),
    sa.Column('recovery_streak', sa.Integer(), nullable=False),
    sa.Column('last_probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outcome', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchdog_rules_site_enabled_status', 'watchdog_rules', ['site_id', 'enabled', 'status'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=True),
    sa.Column('issued_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commands_device_status_expires', 'commands', ['device_id', 'status', 'expires_at'], unique=False)
    op.create_table('device_credentials',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('device_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_events_device_timestamp', 'device_events', ['device_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_device_events_type', 'device_events', ['type'], unique=False)
    op.create_table('device_failsafe_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_version', sa.String(length=40), nullable=True),
    sa.Column('fallback_to_version', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_failsafe_events_device_received', 'device_failsafe_events', ['device_id', sa.literal_column('received_at DESC')], unique=False)
    op.create_table('device_heartbeats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('local_ip', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('relay_on', sa.Boolean(), nullable=True),
    sa.Column('wifi_connected', sa.Boolean(), nullable=True),
    sa.Column('health_state', sa.String(length=40), nullable=True),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('incident_cycles', sa.Integer(), nullable=True),
    sa.Column('hour_cycles', sa.Integer(), nullable=True),
    sa.Column('last_event_type', sa.String(length=80), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_mode', sa.Boolean(), nullable=True),
    sa.Column('auto_recovery_triggered', sa.Boolean(), nullable=True),
    sa.Column('last_known_good_restored', sa.Boolean(), nullable=True),
    sa.Column('consecutive_unhealthy_boots', sa.Integer(), nullable=True),
    sa.Column('in_captive_portal', sa.Boolean(), nullable=True),
    sa.Column('holdoff_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('cooldown_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('central_enabled', sa.Boolean(), nullable=True),
    sa.Column('central_registered', sa.Boolean(), nullable=True),
    sa.Column('central_state', sa.String(length=40), nullable=True),
    sa.Column('central_device_id', sa.String(length=40), nullable=True),
    sa.Column('central_heartbeat_age_seconds', sa.Integer(), nullable=True),
    sa.Column('power_analytics_enabled', sa.Boolean(), nullable=True),
    sa.Column('power_chip_type', sa.String(length=40), nullable=True),
    sa.Column('power_sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('power_batch_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_heartbeats_device_received', 'device_heartbeats', ['device_id', sa.literal_column('received_at DESC')], unique=False)
    op.create_table('device_power_rollups',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('day_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('synthetic_sample_count', sa.Integer(), nullable=True),
    sa.Column('avg_w', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('min_w', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_w', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('kwh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'day_bucket', name='uq_device_power_rollups_device_day')
    )
    op.create_index('ix_device_power_rollups_device_day', 'device_power_rollups', ['device_id', sa.literal_column('day_bucket DESC')], unique=False)
    op.create_table('device_power_samples',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('channel_id', sa.SmallInteger(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sampled_uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_flags', sa.Integer(), nullable=False),
    sa.Column('v_v', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('i_ma', sa.Integer(), nullable=True),
    sa.Column('i_ma_estimated', sa.Boolean(), nullable=True),
    sa.Column('i_ma_estimate', sa.Integer(), nullable=True),
    sa.Column('p_w', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('s_va', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pf', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('hz', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('energy_wh', sa.BigInteger(), nullable=True),
    sa.Column('rssi_dbm', sa.Integer(), nullable=True),
    sa.Column('tx_retry_count', sa.Integer(), nullable=True),
    sa.Column('beacon_miss_count', sa.Integer(), nullable=True),
    sa.Column('crc_fail_count', sa.Integer(), nullable=True),
    sa.Column('chip_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_power_samples_device_channel_sampled', 'device_power_samples', ['device_id', 'channel_id', sa.literal_column('sampled_at DESC')], unique=False)
    op.create_index('ix_device_power_samples_received', 'device_power_samples', [sa.literal_column('received_at DESC')], unique=False)
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('site_id', sa.String(length=40), nullable=True),
    sa.Column('display_name_hint', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_device_id', sa.String(length=40), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_device_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['consumed_by_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_enrollment_tokens_expires_at', 'enrollment_tokens', ['expires_at'], unique=False)
    op.create_index('ix_enrollment_tokens_target_device', 'enrollment_tokens', ['target_device_id'], unique=False)
    op.create_table('firmware_deployments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('force', sa.Boolean(), nullable=False),
    sa.Column('issued_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['firmware_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmware_release_mirrors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_sha256', sa.String(length=64), nullable=True),
    sa.Column('last_probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['firmware_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_firmware_release_mirrors_release', 'firmware_release_mirrors', ['release_id', 'kind'], unique=True)
    op.create_table('group_memberships',
    sa.Column('group_id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'device_id'),
    sa.UniqueConstraint('group_id', 'device_id', name='uq_group_membership')
    )
    op.create_table('watchdog_probe_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=40), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['watchdog_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchdog_probe_events_rule_at', 'watchdog_probe_events', ['rule_id', sa.literal_column('at DESC')], unique=False)
    op.create_table('command_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('command_id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_assignments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('deployment_id', sa.String(length=40), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('last_reported_version', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['firmware_deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['firmware_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignment_device_state', 'deployment_assignments', ['device_id', 'state'], unique=False)
    op.create_table('device_announcements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('mac_address', sa.String(length=40), nullable=False),
    sa.Column('claimed_hardware_model', sa.String(length=80), nullable=True),
    sa.Column('claimed_hardware_revision', sa.String(length=40), nullable=True),
    sa.Column('claimed_firmware_version', sa.String(length=40), nullable=True),
    sa.Column('claimed_local_ip', sa.String(length=64), nullable=True),
    sa.Column('claimed_serial_number', sa.String(length=80), nullable=True),
    sa.Column('claimed_display_name_hint', sa.String(length=120), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('announce_count', sa.Integer(), nullable=False),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adopted_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('adoption_token_secret', sa.String(length=120), nullable=True),
    sa.Column('enrollment_token_id', sa.String(length=40), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adopted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_token_id'], ['enrollment_tokens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_index('ix_device_announcements_last_seen', 'device_announcements', [sa.literal_column('last_seen_at DESC')], unique=False)
    op.create_index('ix_device_announcements_state', 'device_announcements', ['adopted_at', 'consumed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_announcements_state', table_name='device_announcements')
    op.drop_index('ix_device_announcements_last_seen', table_name='device_announcements')
    op.drop_table('device_announcements')
    op.drop_index('ix_assignment_device_state', table_name='deployment_assignments')
    op.drop_table('deployment_assignments')
    op.drop_table('command_results')
    op.drop_index('ix_watchdog_probe_events_rule_at', table_name='watchdog_probe_events')
    op.drop_table('watchdog_probe_events')
    op.drop_table('group_memberships')
    op.drop_index('ix_firmware_release_mirrors_release', table_name='firmware_release_mirrors')
    op.drop_table('firmware_release_mirrors')
    op.drop_table('firmware_deployments')
    op.drop_index('ix_enrollment_tokens_target_device', table_name='enrollment_tokens')
    op.drop_index('ix_enrollment_tokens_expires_at', table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    op.drop_index('ix_device_power_samples_received', table_name='device_power_samples')
    op.drop_index('ix_device_power_samples_device_channel_sampled', table_name='device_power_samples')
    op.drop_table('device_power_samples')
    op.drop_index('ix_device_power_rollups_device_day', table_name='device_power_rollups')
    op.drop_table('device_power_rollups')
    op.drop_index('ix_device_heartbeats_device_received', table_name='device_heartbeats')
    op.drop_table('device_heartbeats')
    op.drop_index('ix_device_failsafe_events_device_received', table_name='device_failsafe_events')
    op.drop_table('device_failsafe_events')
    op.drop_index('ix_device_events_type', table_name='device_events')
    op.drop_index('ix_device_events_device_timestamp', table_name='device_events')
    op.drop_table('device_events')
    op.drop_table('device_credentials')
    op.drop_index('ix_commands_device_status_expires', table_name='commands')
    op.drop_table('commands')
    op.drop_index('ix_watchdog_rules_site_enabled_status', table_name='watchdog_rules')
    op.drop_table('watchdog_rules')
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions')
    op.drop_index('ix_user_sessions_jti', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_schedules_enabled_next_run', table_name='schedules')
    op.drop_table('schedules')
    op.drop_table('runtime_settings')
    op.drop_table('runtime_flags')
    op.drop_index('ix_role_bindings_user', table_name='role_bindings')
    op.drop_index('ix_role_bindings_scope', table_name='role_bindings')
    op.drop_table('role_bindings')
    op.drop_index('ix_password_resets_user_id', table_name='password_resets')
    op.drop_index('ix_password_resets_expires_at', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('ix_invitations_expires_at', table_name='invitations')
    op.drop_index('ix_invitations_email', table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('groups')
    op.drop_table('firmware_releases')
    op.drop_index('ix_external_sensor_samples_source_sampled', table_name='external_sensor_samples')
    op.drop_table('external_sensor_samples')
    op.drop_index('ix_devices_site_id', table_name='devices')
    op.drop_index('ix_devices_mac_address', table_name='devices')
    op.drop_index('ix_devices_last_heartbeat_at', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_target', table_name='audit_events')
    op.drop_index('ix_audit_at_desc', table_name='audit_events')
    op.drop_index('ix_audit_actor', table_name='audit_events')
    op.drop_index('ix_audit_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_attention_acks_snooze_until', table_name='attention_acks')
    op.drop_index('ix_attention_acks_attention_id', table_name='attention_acks')
    op.drop_table('attention_acks')
    op.drop_table('users')
    op.drop_index('ix_unregistered_attempts_last_seen', table_name='unregistered_auth_attempts')
    op.drop_index('ix_unregistered_attempts_claim', table_name='unregistered_auth_attempts')
    op.drop_table('unregistered_auth_attempts')
    op.drop_index('ix_tombstone_entity_type', table_name='tombstones')
    op.drop_index('ix_tombstone_created', table_name='tombstones')
    op.drop_table('tombstones')
    op.drop_index('ix_sync_cursor_updated', table_name='sync_cursors')
    op.drop_table('sync_cursors')
    op.drop_table('sites')
    op.drop_index('ix_signup_requests_status', table_name='signup_requests')
    op.drop_index('ix_signup_requests_email', table_name='signup_requests')
    op.drop_index('ix_signup_requests_created_at', table_name='signup_requests')
    op.drop_table('signup_requests')
    op.drop_table('scenes')
    op.drop_index('ix_outbox_tombstone', table_name='outbox_events')
    op.drop_index('ix_outbox_seq', table_name='outbox_events')
    op.drop_index('ix_outbox_entity', table_name='outbox_events')
    op.drop_index('ix_outbox_at', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('external_sensor_sources')
    op.drop_index('ix_epg_cache_lookup', table_name='external_epg_cache')
    op.drop_index('ix_epg_cache_airing_end', table_name='external_epg_cache')
    op.drop_table('external_epg_cache')
    op.drop_index('ix_audit_archive_at_desc', table_name='audit_events_archive')
    op.drop_index('ix_audit_archive_archived_at', table_name='audit_events_archive')
    op.drop_table('audit_events_archive')
    # ### end Alembic commands ###
